networks:
  smartmes:
    driver: bridge

services:
  backendApp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: smartmes-chat-server
    container_name: smartmes-chat-server
    restart: on-failure
    environment:
      DB_HOST: mysql
    networks:
      - smartmes
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  reactApp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: smartmes-chat-client
    container_name: smartmes-chat-client
    restart: on-failure
    environment:
      SERVER_HOST: backendApp
    networks:
      - smartmes
    ports:
      - "8080:3000"
    depends_on:
      - backendApp

  mysql:
    image: mysql:8.0.20
    container_name: smartmes-mysql-db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: chat_db
      TZ: America/Belem
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/docker-entrypoint-initdb.d/
    networks:
      - smartmes

volumes:
  mysql-data:
    driver: local
