networks:
  smartmes:
    driver: bridge

services:
  backendApp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: smartmes-chat-server
    container_name: smartmes-chat-server
    restart: on-failure
    networks:
      - smartmes
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  reactApp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: smartmes-chat-client
    container_name: smartmes-chat-client
    restart: on-failure
    networks:
      - smartmes
    ports:
      - "3000:3000"
    depends_on:
      - backendApp
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - smartmes
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
